name: Sync and Create Weekly Release for Original Repo

on:
  schedule:
    - cron: '0 0 * * 5'  # Runs every Thursday at midnight

jobs:
  sync-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout forked repo
        uses: actions/checkout@v3
        with:
          repository: aaarkai/vllm_sail
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync with original repo
        run: |
          git remote add original https://github.com/vllm-project/vllm.git
          git fetch original
          git merge original/main

      - name: Get current date
        id: get-date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create release for original repo
        uses: softprops/action-gh-release@v1
        with:
          repository: aaarkai/vllm_sail
          tag_name: weekly-${{ steps.get-date.outputs.date }}
          name: Weekly Release ${{ steps.get-date.outputs.date }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
